name: Clang Tidy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

    - name: Install clang-tidy
      run: sudo apt-get install clang-tidy

    - name: Run clang-tidy
      working-directory: ${{runner.workspace}}/build
      run: run-clang-tidy
