name: CMake

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: "${{ matrix.configurations.name }} | ${{ matrix.cmake-build-type }}"
    runs-on: ${{ matrix.configurations.os }}
    env:
      CONAN_SYSREQUIRES_MODE: enabled
    strategy:
      fail-fast: false
      matrix:
        configurations:
          - name: Ubuntu 18.04
            os: ubuntu-18.04
          - name: Ubuntu 20.04
            os: ubuntu-20.04
          - name: Windows 2019
            os: windows-2019
        cmake-build-type: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive

    - name: Fix Path on Ubuntu
      if: matrix.configurations.os == 'ubuntu-20.04' || matrix.configurations.os == 'ubuntu-18.04'
      run: echo "/home/runner/.local/bin" >> $GITHUB_PATH

    - name: Get Clang 11 on Ubuntu
      if: matrix.configurations.os == 'ubuntu-20.04' || matrix.configurations.os == 'ubuntu-18.04'
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

    - name: Bootstrap VCPKG
      if: matrix.configurations.os == 'ubuntu-20.04' || matrix.configurations.os == 'ubuntu-18.04'
      run: $GITHUB_WORKSPACE/vcpkg/bootstrap-vcpkg.sh

    - name: Bootstrap VCPKG
      if: matrix.configurations.os == 'windows-2019'
      run: $GITHUB_WORKSPACE\\bootstrap-vcpkg.bat

    - name: Configure CMake
      working-directory: $GITHUB_WORKSPACE
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      run: cmake -B ${{runner.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.cmake-build-type }}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config ${{ matrix.cmake-build-type }}

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{ matrix.cmake-build-type }}
